# 这个配置文件中我只提供了部署claude3所需配置，如有其他需求，请参考官方repo的配置文件
version: "3"
services:
  gpt_academic_nolocalllms:
    image: claude-academic:latest
    environment:
      # 请查阅 `config.py` 以查看所有的配置信息
      # 请配置你的ANTHROPIC_API_KEY
      ANTHROPIC_API_KEY: "    sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                            "
      # 如需配置代理，请取消注释下面两行，并修改代理地址
      # USE_PROXY: "    True                                                                                           "
      # proxies: '    { "http": "socks5h://localhost:10880", "https": "socks5h://localhost:10880", }                 '
      LLM_MODEL: "    claude-3-sonnet-20240229                                                                                  "
      AVAIL_LLM_MODELS: '    ["claude-instant-1.2","claude-2.0","claude-2.1","claude-3-sonnet-20240229","claude-3-opus-20240229"]         '
      WEB_PORT: "    22303                                                                                          "
      ADD_WAIFU: "    True                                                                                           "

    # network_mode: "host"  # 宿主网络融合模式
    # 采用端口暴露的方式，可以自行修改为与宿主网络融合的模式
    ports:
      - "22303:22303" # 必须与WEB_PORT相互对应

    # 不使用代理网络拉取最新代码
    command: >
      bash -c "python3 -u main.py"
